# Generated by Django 3.1.7 on 2021-03-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga_binaan', '0003_auto_20210304_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prison',
            name='pasal',
            field=models.CharField(max_length=100),
        ),
    ]
